// This file has been autogenerated. The following properties could not be retrieved from the API or would not make sense in a different org e.g. Edge IDs
// The variables contained in this file have been given default values and should be edited as necessary

genesyscloud_flow_COMMONMODULE_2445093_Lang_filepath = ""
genesyscloud_flow_INQUEUECALL_2445093_F_InQueue_filepath = ""
genesyscloud_integration_credential_Integration-GenC1_Data_Actions_fields = null