###
# This action runs the Genesys Cloud export locally (not via Terraform Cloud)
# so the exported files are available in the GitHub Actions workspace
###
name: "Export Genesys Cloud Queues"
description: "Export Genesys Cloud queue configurations to .tf files"
runs:
  using: "composite"
  steps:
    - run: |
        cd $GITHUB_WORKSPACE/blueprint/genesys-cloud-cx-as-code/export
        terraform init
        terraform apply -auto-approve
        cd $GITHUB_WORKSPACE
      shell: bash
